<a href="https://colab.research.google.com/github/HobbsJacob37/Snoasis/blob/main/nonyellownsnow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## data cleaned

cleaned data. added month column and removed question marks from time

In [15]:
import pandas as pd
import matplotlib.pyplot as plt
import calendar

In [16]:
df = pd.read_csv('https://raw.githubusercontent.com/camdenlol/SnOasis/main/snoasisData.csv')

In [17]:
df.Time.loc[0][:-3]+" "+df.Time.loc[0][-2:]

'7:50:56 PM'

In [18]:
def getRidOfQuestion(string):
  return string[:-3]+" " +string[-2:]

In [19]:
 df.Time = df.Time.apply(getRidOfQuestion)

In [20]:
df.Date=pd.to_datetime(df.Date, format = '%m/%d/%Y')

In [21]:
df["MonthName"] = df.Date.dt.month_name()

In [25]:
df['Time'] = pd.to_datetime(df['Time'])

# Convert AM/PM time to 24-hour format
df['Time'] = df['Time'].dt.strftime('%H:%M:%S')

In [26]:
df

,Date,Time,Staff,Receipt number,Name,Variant,Unit,Quantity,Price (USD),Discount (USD),Subtotal (USD),Tax Info Available,Is Tax Exempt,Total tax collected (USD),Final price (USD),SKU,Barcode,Cost price,Comment,MonthName
0,2023-02-28,19:50:56,SnOasis Main,1,Gift card,NaN,NaN,1,1.0,0.0,1.0,No,No,0.00,1.00,NaN,NaN,0.0,NaN,February
1,2023-02-28,19:52:12,SnOasis Main,2,Gift card,NaN,NaN,1,1.0,0.0,1.0,No,No,0.00,1.00,NaN,NaN,0.0,NaN,February
2,2023-02-28,19:58:14,SnOasis Main,3,Gift card,NaN,NaN,1,1.0,0.0,1.0,No,No,0.00,1.00,NaN,NaN,0.0,NaN,February
3,2023-02-28,20:21:15,SnOasis Main,4,Candy Bar,NaN,NaN,1,1.5,0.0,1.5,Yes,No,0.14,1.64,NaN,NaN,0.0,NaN,February
4,2023-02-28,21:29:15,SnOasis East,5,Gift card,NaN,NaN,1,1.0,0.0,1.0,No,No,0.00,1.00,NaN,NaN,0.0,NaN,February
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76214,2023-11-05,17:42:06,SnOasis Main,37192,Small,NaN,NaN,2,2.0,0.0,2.0,Yes,No,0.19,2.19,NaN,NaN,0.0,NaN,November
76215,2023-11-05,17:44:05,SnOasis Main,37193,Small,NaN,NaN,2,2.0,0.0,2.0,Yes,No,0.19,2.19,NaN,NaN,0.0,NaN,November
76216,2023-11-05,17:48:20,SnOasis Main,37194,Small,NaN,NaN,2,2.0,0.0,2.0,Yes,No,0.19,2.19,NaN,NaN,0.0,NaN,November
76217,2023-11-05,17:51:32,SnOasis Main,37195,Small,NaN,NaN,2,2.0,0.0,2.0,Yes,No,0.19,2.19,NaN,NaN,0.0,NaN,November
76218,2023-11-05,17:58:17,SnOasis Main,37196,Small,NaN,NaN,1,1.0,0.0,1.0,Yes,No,0.09,1.09,NaN,NaN,0.0,NaN,November